events {}
http {
    server {
        listen 80 default backlog=16384;
        listen [::]:80 default backlog=16384;

        # ---------- 1) JS kitaplıkları ----------
        location /libs/ {
            proxy_pass https://cdn.mxpnl.com/libs/;
            proxy_set_header Host cdn.mxpnl.com;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host $server_name;
        }

        # ---------- 2) Session Replay JS ----------
        # (Artık /libs/ kuralı yakaladığı için ayrı şarta gerek yok)

        # ---------- 3) In-app messages & A/B test asset'leri ----------
        location /site_media/ {
            proxy_pass https://cdn.mxpnl.com/site_media/;
            proxy_set_header Host cdn.mxpnl.com;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host $server_name;
        }

        # ---------- 4) decide endpoint ----------
        location = /decide {
            proxy_pass https://decide.mixpanel.com/decide;
            proxy_ssl_server_name on;
            proxy_set_header Host decide.mixpanel.com;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host $server_name;
        }

        # ---------- 5) tüm API çağrıları ----------
        location /mp/ {
            proxy_pass https://api.mixpanel.com/;
            proxy_ssl_server_name on;
            proxy_set_header Host api.mixpanel.com;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host $server_name;
        }
    }
}
