events {}
http {
    resolver 8.8.8.8 8.8.4.4 ipv6=off;

    server {
        listen 80 default backlog=16384;
        listen [::]:80 default backlog=16384;
        server_name m.nonresident.tax;


        location /libs/ {
            proxy_pass https://cdn.mxpnl.com/libs/;
            proxy_set_header Host cdn.mxpnl.com;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host $server_name; 
        }

        location /site_media/ {
            set $upstream_host "cdn.mxpnl.com";
            proxy_pass https://$upstream_host/site_media/;
            proxy_set_header Host $upstream_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host $server_name; 
        }

        location = /decide {
            set $upstream_host "decide.mixpanel.com";
            proxy_pass https://$upstream_host/decide;
            proxy_ssl_server_name on;
            proxy_set_header Host $upstream_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host $server_name;
        }

        location /track {
            set $upstream_host "api.mixpanel.com";
            proxy_pass https://$upstream_host;
            proxy_ssl_server_name on;
            proxy_set_header Host $upstream_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host $server_name;
        }

        location /engage {
            set $upstream_host "api.mixpanel.com";
            proxy_pass https://$upstream_host;
            proxy_ssl_server_name on;
            proxy_set_header Host $upstream_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host $server_name;
        }

        location /groups {
            set $upstream_host "api.mixpanel.com";
            proxy_pass https://$upstream_host;
            proxy_ssl_server_name on;
            proxy_set_header Host $upstream_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host $server_name;
        }

        location /record {
            set $upstream_host "api.mixpanel.com";
            proxy_pass https://$upstream_host;
            proxy_ssl_server_name on;
            proxy_set_header Host $upstream_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host $server_name;
        }
    }
}
